# -*- coding: utf-8 -*-
"""01_download_datas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MWMTXoHatoGkYRPErFOWqMRo0xd_Vk8E
"""

# script for download datas from kaggle
# doc : 
# https://www.kaggle.com/general/74235

from google.colab import drive
drive.mount('/drive') # 4/1AA...

!pip install -q kaggle

from google.colab import files

files.upload()

! mkdir /drive/MyDrive/asdpy/data
! cp kaggle.json /drive/MyDrive/asdpy/data/
! chmod 600 /drive/MyDrive/asdpy/data/kaggle.json
! kaggle datasets list

!kaggle datasets download -d daisukelab/dc2020task2 -p /drive/MyDrive/asdpy/data/original

! cd /drive/MyDrive/asdpy/data/original
! mkdir /drive/MyDrive/asdpy/data/original/dc2020task2
! unzip /drive/MyDrive/asdpy/data/original/dc2020task2.zip -d /drive/MyDrive/asdpy/data/original/dc2020task2

ls /drive/MyDrive/asdpy/data/original/dc2020task2